### GENERAL SETTINGS ###

# Site settings
title: PAXCOM
keywords: "Centralized Product information management"
description: Customizable Dashboards for Deep Insights into Key Performance Indicators of your business.

### Build settings
markdown: kramdown
highlighter: pygments

# Site Navigation
baseurl: /paxtrial
